### ISSUE TITLE
Can sort everything Atleast alphabetical in the list e.g aradhana 1 is way below in the list

 :Feature Request

### ISSUE THREAD

**Issue by VatsaPatel** [AnoopamMission/iOS-App-Feedback#44]
TF - Rutvik Rana:
Device: iPhone 11 Pro
Location: USA

Feature Request:

Can sort everything Atleast alphabetical in the list e.g aradhana 1 is way below in the list

https://drive.google.com/open?id=1p-xWbvCzNLPKp5f71wYx0tpx2uE9Q5Ej

**Comment by ddesai** [comment]
Available in v1.3#3
