### ISSUE TITLE
Instead of showing the album title underneath each track, can you display the artist name?
 :TF - Mihir Patel

### ISSUE THREAD

**Issue by VatsaPatel** [AnoopamMission/iOS-App-Feedback#46]
TF - Mihir Patel:
Device: iPhone 8
Location: USA

Questions:

Instead of showing the album title underneath each track, can you display the artist name?

https://drive.google.com/open?id=1mkhKCzpN3_YdnJyN0lNKCAPdnezGiHp7

**Comment by ddesai** [comment]
Fixed in v1.3#3.
